// <auto-generated />
namespace Lorenzo_InterTransit_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lolow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lolow));
        
        string IMigrationMetadata.Id
        {
            get { return "201707261829020_lolow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
